name: Deploy to Railway

on:
  release:
    types:
      - created

jobs:
  login_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_DOCKER_API }}:${IMAGE_TAG} -f docker/proxy-server/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_DOCKER_API }}:${IMAGE_TAG}

  cleanup:
        needs: login_push_image
        runs-on: ubuntu-latest
          
        steps:
          - name: Configure Docker
            run: |
                  echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login ghcr.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          
          - name: List Docker images
            run: docker images
          
          - name: Remove old Docker images
            run: |
                  IMAGES=$(docker images ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_DOCKER_API }} -q)
                  echo "$IMAGES" | while read -r IMAGE_ID; do
                    docker image rm ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_DOCKER_API }}:"$IMAGE_ID" --force
                  done
          
          
