name: Deploy to AWS

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  login_push_image:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_DOCKER_API }}:latest -f docker/proxy-server/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_DOCKER_API }}:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Update ECS service with new task
        run: |
            echo "::set-env name=SERVICE_NAME::app"
            echo "::set-env name=CLUSTER_NAME::ecs-cluster4"
            PREVIOUS_TASK=$(aws ecs list-tasks --service-name $SERVICE_NAME --cluster $CLUSTER_NAME --desired-status RUNNING --output text | awk '{print $NF}')
            aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
          
      - name: Stop previous task
        run: |
          if [ -n "$PREVIOUS_TASK" ]; then
            aws ecs stop-task --task $PREVIOUS_TASK --cluster $CLUSTER_NAME
          fi
